FengZhen.Restaurant/FengZhen.Restaurant.WebApp/Controllers/AdminController.cs
using FengZhen.Restaurant.Domain.Abstract;
using FengZhen.Restaurant.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FengZhen.Restaurant.WebApp.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private IFoodsRepository repository;

        public AdminController(IFoodsRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index()
        {
            return View(repository.FoodsList);
        }

        public ViewResult Edit(int foodId)
        {
            Food food = repository.FoodsList
            .FirstOrDefault(p => p.FoodId == foodId);
            return View(food);
        }

        [HttpPost]
        public ActionResult Edit(Food food, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    food.ImageMimeType = image.ContentType;
                    food.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(food.ImageData, 0, image.ContentLength);
                }
                repository.SaveFood(food);
                TempData["message"] = string.Format("{0} has been saved.", food.Name);
                return RedirectToAction("Index");
            }
            else
            {
                return View(food);
            }
        }

        public ViewResult Create()
        {
            return View("Edit", new Food());
        }

        [HttpPost]
        public ActionResult Delete(int foodId)
        {
            Food food = repository.DeleteFood(foodId);
            if(food !=null)
            {
                TempData["message"] = string.Format("{0} has been deleted.", food.Name);
            }
            return RedirectToAction("Index");
        }

    }
}

FengZhen.Restaurant/FengZhen.Restaurant.WebApp/Controllers/FoodController.cs
using FengZhen.Restaurant.Domain.Abstract;
using FengZhen.Restaurant.Domain.Entities;
using FengZhen.Restaurant.WebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FengZhen.Restaurant.WebApp.Controllers
{
    public class FoodController : Controller
    {
        public const int PageSize = 5;

        public IFoodsRepository FoodsRepository { get; set; }

        //// GET: Food
        //public ActionResult Index()
        //{
        //    return View();
        //}

        public ViewResult List(string category, int page = 1)
        {
            FoodsListViewModel model = new FoodsListViewModel
            {
                currentCategory = category,

                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = FoodsRepository.FoodsList.Where(f => category == null || f.Category == category).Count()
                },

                Foods = FoodsRepository.FoodsList
                .Where(f => category == null || f.Category == category)
                .OrderBy(f => f.FoodId)
                .Skip((page - 1) * PageSize)
                .Take(PageSize)
            };

            return View(model);
        }

        public FileContentResult GetImage(int foodId)
        {
            Food foodItem = FoodsRepository.FoodsList.FirstOrDefault(x => x.FoodId == foodId);

            if (foodItem != null)
            {
                return File(foodItem.ImageData, foodItem.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

FengZhen.Restaurant/FengZhen.Restaurant.WebApp/Views/Admin/Edit.cshtml
@model FengZhen.Restaurant.Domain.Entities.Food
@{
    ViewBag.Title = "Admin: Edit " + @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    HtmlHelper.ClientValidationEnabled = true;
    HtmlHelper.UnobtrusiveJavaScriptEnabled = true;
}
    <div class="panel">
        <div class="panel-heading">
            <h3>Edit @Model.Name</h3>
        </div>
        @using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="panel-body">
                @Html.HiddenFor(m => m.FoodId)
                @foreach (var property in ViewData.ModelMetadata.Properties)
                {
                    switch(property.PropertyName)
                    {
                        case "FoodId":
                        case "ImageData":
                        case "ImageMimeType":
                            // do nothing
                            break;
                        default:
                            <div class="form-group">
                                <label>@(property.DisplayName ?? property.PropertyName)</label>
                                @if (property.PropertyName == "Description")
                                {
                                    @Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = 5 })
                                }
                                else
                                {
                                    @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                                }
                            @Html.ValidationMessage(property.PropertyName)
                            </div>
                            break;
                    }
                }
                <div class="form-group">
                    <div style="position:relative;">
                        <label>Image</label>
                        <a class='btn' href='javascript:;'>
                            Choose File...
                            <input type="file" name="Image" size="40"
                                   style="position:absolute;z-index:2;top:0;left:0;filter: alpha(opacity=0);
                                   opacity:0;background-color:transparent;color:transparent;"
                                   onchange='$("#upload-file-info").html($(this).val());'>
                        </a>
                        <span class='label label-info' id="upload-file-info"></span>
                    </div>
                    @if (Model.ImageData == null)
                    {
                        <div class="form-control-static">
                            <img id="NoImg" class="img-thumbnail" width="250" height="250" style="display:none" />
                        </div>
                    }
                    else
                    {
                        <img id="WithImg" class="img-thumbnail" width="250" height="250"
                             src="@Url.Action("GetImage", "Food",new { Model.FoodId })" />
                    }
                </div>
            </div>
            <div class="panel-footer">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Cancel and return to List", "Index", null, new
                {
                @class = "btn btn-default"
                })
            </div>
        }
    </div>
<script type="text/javascript" src="~/Scripts/javascript.LoadImge.js"></script>

FengZhen.Restaurant/FengZhen.Restaurant.WebApp/Views/Admin/Index.cshtml
@model IEnumerable<FengZhen.Restaurant.Domain.Entities.Food>
@{
    ViewBag.Title = "Admin: All Foods";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    HtmlHelper.ClientValidationEnabled = true;
    HtmlHelper.UnobtrusiveJavaScriptEnabled = true;
}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>All Foods</h3>
        </div>
        <div class="panel-body">
            <table class="table table-striped table-condensed table-bordered">
                <tr>
                    <th class="text-right">Id</th>
                    <th class="text-left">Name</th>
                    <th class="text-right">Price</th>
                    <th class="text-center">Option</th>
                </tr>
                @foreach(var item in Model)
                {
                    <tr>
                        <td class="text-right">@item.FoodId</td>
                        <td class="text-left">@Html.ActionLink(item.Name, "Edit", new { item.FoodId })</td>
                        <td class="text-right">@item.Price.ToString("c")</td>
                        <td class="text-center">
                            @using (Html.BeginForm("Delete", "Admin"))
                            {
                                @Html.Hidden("foodId", item.FoodId)
                                <input type="submit" class="btn btn-default btn-xs" value="Delete" />
                            }
                        </td>
                    </tr>
                }
            </table>
        </div>
        <div class="panel-footer">
            @Html.ActionLink("Add a new food", "Create", null,new { @class = "btn btn-default" })
        </div>
    </div>