FengZhen.Restaurant/FengZhen.Restaurant.WebApp/Controllers/FoodController.cs
using FengZhen.Restaurant.Domain.Abstract;
using FengZhen.Restaurant.Domain.Entities;
using FengZhen.Restaurant.WebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FengZhen.Restaurant.WebApp.Controllers
{
    public class FoodController : Controller
    {
        public const int PageSize = 5;

        public IFoodsRepository FoodsRepository { get; set; }

        //// GET: Food
        //public ActionResult Index()
        //{
        //    return View();
        //}

        public ViewResult List(string category, int page = 1)
        {
            FoodsListViewModel model = new FoodsListViewModel
            {
                currentCategory = category,

                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = FoodsRepository.FoodsList.Where(f => category == null || f.Category == category).Count()
                },

                Foods = FoodsRepository.FoodsList
                .Where(f => category == null || f.Category == category)
                .OrderBy(f => f.FoodId)
                .Skip((page - 1) * PageSize)
                .Take(PageSize)
            };

            return View(model);
        }

        public FileContentResult GetImage(int foodId)
        {
            Food foodItem = FoodsRepository.FoodsList.FirstOrDefault(x => x.FoodId == foodId);

            if (foodItem != null)
            {
                return File(foodItem.ImageData, foodItem.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

FengZhen.Restaurant/FengZhen.Restaurant.WebApp/Controllers/NavController.cs
using FengZhen.Restaurant.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FengZhen.Restaurant.WebApp.Controllers
{
    public class NavController : Controller
    {
        private IFoodsRepository repository;

        public NavController(IFoodsRepository repo)
        {
            repository = repo;
        }

        //public PartialViewResult Menu(string category = null)
        //{
        //    ViewBag.SelectedCategory = category;

        //    IEnumerable<string> categories = repository
        //    .FoodsList
        //    .Select(x => x.Category)
        //    .Distinct()
        //    .OrderBy(x => x);
        //    return PartialView(categories);
        //}

        //public PartialViewResult Menu(string category = null, bool horizontalLayout = false)
        //{
        //    ViewBag.SelectedCategory = category;
        //    IEnumerable<string> categories = repository
        //    .FoodsList
        //    .Select(x => x.Category)
        //    .Distinct()
        //    .OrderBy(x => x);
        //    string viewName = horizontalLayout ? "MenuHorizontal" : "Menu";
        //    return PartialView(viewName, categories);
        //}

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository
            .FoodsList
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x);
            return PartialView("FlexMenu", categories);
        }
    }
}

FengZhen.Restaurant/FengZhen.Restaurant.WebApp/Views/Shared/FoodSummary.Mobile.cshtml
@model FengZhen.Restaurant.Domain.Entities.Food
<div data-role="collapsible" data-collapsed="false" data-content-theme="c">
    <h2>
        @Model.Name
    </h2>
    <div class="ui-grid-b">
        <div class="ui-block-a">
            @Model.Description
        </div>
        <div class="ui-block-b">
            <strong>(@Model.Price.ToString("c"))</strong>
        </div>
        <div class="ui-block-c">
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                @Html.HiddenFor(x => x.FoodId)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" data-inline="true" data-mini="true" value="Add to cart" />
            }
        </div>
    </div>
</div>

FengZhen.Restaurant/FengZhen.Restaurant.WebApp/Views/Shared/FoodSummary.cshtml
@model FengZhen.Restaurant.Domain.Entities.Food

    <div class="well">
        @if (Model.ImageData != null)
        {
            <div class="pull-left" style="margin-right: 10px">
                <img class="img-thumbnail" width="75" height="75"
                     src="@Url.Action("GetImage", "Food", new { Model.FoodId })" />
            </div>
        }
        <h3>
            <strong>@Model.Name</strong>
            <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
        </h3>

        @using (Html.BeginForm("AddToCart", "Cart"))
        {
            <div class="pull-right">
                @Html.HiddenFor(x => x.FoodId)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="Add to cart" />
            </div>
        }
        <span class="lead"> @Model.Description</span>
    </div>

FengZhen.Restaurant/FengZhen.Restaurant.WebApp/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

FengZhen.Restaurant/FengZhen.Restaurant.WebApp/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
          href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div data-role="page" id="page1">
        <div data-theme="a" data-role="header" data-position="fixed">
            <h3>RESTAURANT Mobile</h3>
            @Html.Action("Menu", "Nav")
        </div>
        <div data-role="content">
            <ul data-role="listview" data-divider-theme="b" data-inset="false">
                @RenderBody()
            </ul>
        </div>
    </div>
</body>
</html>

FengZhen.Restaurant/FengZhen.Restaurant.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title>@ViewBag.Title</title>
    <style>
        .navbar-right {
            float: right !important;
            margin-right: 15px;
            margin-left: 15px;
        }
    </style>
</head>
<body>
    <!--<div class="navbar navbar-default" role="navigation">-->
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">
            <span class="hidden-xs">ONLINE RESTAURANT</span>
            <div class="visible-xs">ONLINE</div>
            <div class="visible-xs">RESTAURANT</div>
        </a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="visible-xs">
        @Html.Action("Menu", "Nav", new { horizontalLayout = true })
    </div>
    <div class="row panel">
        <div id="categories" class="col-sm-3 hidden-xs">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-12 col-sm-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>